name: Deploy VPC to AWS

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: envs/dev/vpc

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Fix
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
